const phrases = [
    "It’s 100% off if you don’t buy it.",
    "Not wanting something is as good as having it.",
    "Someone else’s success isn’t your failure.",
    "A question opens the mind, a statement keeps it closed.",
    "Time spent on things you can't control takes time away from things you can.",
    "Being creative is just combining interest with initiative.",
    "Success, like happiness, cannot be pursued. It must ensue.",
    "Value compliments and insults the same.",
    "Consuming information won't make you smart, applying it will.",
    "Be happy with what you have, while you work for what you want.",
    "Life is too short to not be pursuing the best opportunity you know of.",
    "Inspiration is a productivity multiplier, but it’s perishable. Act quickly.",
    "Minimalism isn't about owning nothing, it’s about nothing owning you.",
    "Demotivated because of how long it takes? The time will pass anyways.",
    "People don't care what you can do, they care about what you can do for them.",
    "How much you eat affects your size, how much you move affects your shape.",
    "Not having the time for it is another way of saying it’s not important.",
    "Choose consistency over intensity, because consistency compounds.",
    "Most traditions are solutions to forgotten problems.",
    "You were born in one day, you will die in one day, you can change in one day.",
    "Yesterday is gone, tomorrow isn't promised, today is all there is.",
    "Focus on nothing when it doesn’t matter, so you’ll focus better when it does.",
    "More choices often lead to less action. Do more by doing less.",
    "It’s not the thing itself that upsets you, but your interpretation of it.",
    "Focus is repeatedly saying no to almost everything.",
    "You can either build your dream, or help someone build theirs.",
    "Stop trading time for money, start trading value for money.",
    "Learning how to learn is one of the best investments of your time.",
    "Your circumstances have nothing to do with your emotional state.",
    "Discipline is choosing between what you want now and what you want most.",
    "The real value of money is what you can afford to no longer do.",
    "If you lower your expectations, you’ll rarely be disappointed.",
    "Creativity is an infinite resource—the more you spend, the more you have.",
    "Every 'no' improves your ability to fulfill on a future yes.",
    "The gap between where you are and where you want to be is closer than you think.",
    "Your ideas are worth nothing without the will to act on them.",
    "Be interesting to others by being interested in them.",
    "Every single person you meet knows something you don’t.",
    "Speak when you have something to say, not when you want to say something.",
    "Mediocrity is the path of least resistance, also making it the most competitive.",
    "Being busy is not a badge of honor—it's a lack of freedom.",
    "Your thoughts and feelings are choices. Control them or they'll control you.",
    "You don't lack motivation, you lack a better reason.",
    "Time is your most valuable resource, spend it wisely.",
    "Admit when you’re wrong, show humility when you’re right.",
    "Your brain doesn’t fill up with more information, it expands along with it.",
    "If it takes less than 5 minutes, don’t schedule it, do it now.",
    "Your biggest competitor in life is yourself.",
    "Life only gives you what you decided you could have.",
    "The internet removes the barrier from how much you can learn about anything.",
    "Ignore the noise, people will criticize you no matter what you do.",
    "Avoiding stupidity can often be a better strategy than seeking out brilliance.",
    "If you have time to consume, you have time to create.",
    "There’s no right or wrong time, there’s just time and what you choose to do with it.",
    "You can steal all the ideas you want, but action can only come from within.",
    "Get comfortable with changing your mind after learning new information.",
    "Food fuels your brain, information fuels your mind. You are what you consume.",
    "Read to find new ideas, write to understand them, implement to learn from them.",
    "Your current habits are a sneak peek of your desired future.",
    "The best teachers are your previous mistakes.",
    "Working hard doesn’t get you anywhere if you’re working on the wrong thing.",
    "Being alone is physical, feeling alone is mental.",
    "Silence is a blank canvas for your thoughts.",
    "If it doesn't feel like work, no one can compete with you.",
    "Compare upwards and feel envy, compare downwards and feel grateful.",
    "You are not what you say or think, you are what you do.",
    "There are no million dollar ideas, only million dollar executions.",
    "What you believe is what you settle for.",
    "Saying yes benefits others, saying no benefits you.",
    "The quality of your mind determines the quality of your life.",
    "Being great is just being consistently good.",
    "Spending time on things that buy you time is always a good use of it.",
    "The dots only connect in retrospect.",
    "Consuming puts you to work for the internet, creating puts the internet to work for you.",
    "Hours don't equal output.",
    "Luck favors those in motion.",
    "The only difference between creators & consumers is the willingness to publish.",
    "If you never get bored of learning, you'll never get tired of living.",
    "The more you move, the easier it is to keep moving.",
    "The only productivity hack you need is enjoying what you do.",
    "How you do anything, is how you do everything.",
    "Beliefs are more about belonging than they are about truth.",
    "Continuous improvement is better than delayed perfection.",
    "Do many things that you like to find the few things that you love.",
    "Your first impression isn’t your appearance, it’s your energy.",
    "You're not bad at something, you're just new to it.",
    "Death is the price we pay for life, learn to make peace with it.",
    "The sooner you pay the price, the less it will cost you in the long run.",
    "Motivation more often comes after starting, not before.",
    "Integrity is being the same person no matter the circumstance.",
    "Increase your rate of success by increasing your rate of failure.",
    "The cost of anything in life is either money, time, or attention.",
    "Discipline is doing what you hate to do as if you love it.",
    "The less you have to work with, the more you'll do with what you have.",
    "Absorb what's useful, discard what isn't, add what's uniquely yours.",
    "Most bad things in life come from too much or too little of any one thing.",
    "If you’re reading this, you have everything you need to start.",
    "Peace is the absence of desire.",
    "No one owes you anything."
];

function getRandomPhrase() {
    const randomIndex = Math.floor(Math.random() * phrases.length)
    return phrases[randomIndex];
}

document.getElementById("motivate-btn").addEventListener("click", function() {
    const phrase = getRandomPhrase ();
    document.getElementById ("phrase").textContent = phrase;
});